services:
  api:
    image: simplebank
    ports:
      - "8080:8080"
    environment:
      DB_DRIVER: $DB_DRIVER
      DB_SOURCE: $DB_SOURCE
      SERVER_ADDRESS: $SERVER_ADDRESS
      TOKEN_SYMMETRIC_KEY: $TOKEN_SYMMETRIC_KEY
      ACCESS_TOKEN_DURATION: $ACCESS_TOKEN_DURATION
  pg:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $MY_EMAIL
      PGADMIN_DEFAULT_PASSWORD: secret

  adminer:
    image: adminer
    ports:
      - "9998:8080"

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations

  sqlc:
    image: kjconroy/sqlc
    volumes:
      - .:/src
    working_dir: /src


