services:
  api:
#    image: golang:1.18
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "38000:38000"
  pg:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $MY_EMAIL
      PGADMIN_DEFAULT_PASSWORD: secret

  adminer:
    image: adminer
    ports:
      - "9998:8080"

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations

  sqlc:
    image: kjconroy/sqlc
    volumes:
      - .:/src
    working_dir: /src


