apiVersion: v1
data:
  mapUsers: |
    - userarn: arn:aws:iam::988726194909:user/github-ci
      username: github-ci
      groups:
      - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
