name: Run unit tests

on:
  push:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
#    container: golang:1.18
    services:
      # Label used to access the service container
      pg:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_DB: simple_bank
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:


      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
          cache: true
        id: go

      - name: Prepare Env File
        run: cp app.env.example app.env

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

#      - name: Build
#        run: go build -v .

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin
          which migrate

      - name: Run migrations
        run: migrate -path ./db/migrations -database "postgres://root:secret@localhost:5432/simple_bank?sslmode=disable" -verbose up

      - name: Test
        run: go test -v -cover ./...



